### ISSUE TITLE
climetlab should not require branca==0.3.1

### ISSUE THREAD

**Issue by thebaptiste** [ecmwf/climetlab#46]
`https://github.com/python-visualization/branca/issues/81` is now closed
So climetlab should probably not require anymore `branca==0.3.1`

**Comment by floriankrb** [comment]
Yes, I guess the setup.py could then be updated to `branca<=0.3.1,branca>=...`
Do you want to submit a PR?

**Comment by thebaptiste** [comment]
It's difficult for me to submit a PR because : 
- I don't know what is exactly climetlab problem with branca>0.3.1, I only know that the branca issue is referenced in `setup.py`
- the branca issue is closed not because of a change in branca, but because of a new folium support in streamlit with streamlit-folium library (see https://github.com/python-visualization/branca/issues/81#issuecomment-1304563574)
So I don't know if the climetlab problem would be resolved by changing branca dependency, or changing folium dependency, or adding streamlit-folium dependency...

If you give me the scenario to reproduce the problem, I could make some tests and maybe then submit a PR.

My problem is that a would like to use climetlab and other packages requiring branca>0.3.1 in the same python program...

**Comment by floriankrb** [comment]
This was introduced to make sure this notebook works, for interactive maps: https://climetlab.readthedocs.io/en/latest/examples/17-interactive-maps.html 
This notebook is expected to work when we install `pip install climetlab[interactive]`

At this time we had to install the dependencies  "skinnywms" and "folium>=0.12.1" (see in the setup.py, the extra "interactive").
Since it causes weird dependency problems with branca versions and the most robust solution were to set branca>0.3.1.

I suggest using this notebook as a test (there are no test on this interactive map, this is a very experimental feature). If it still works, as long as the other tests, we are good to go.

**Comment by thebaptiste** [comment]
Sorry, I don't have the time nor the competencies (not a folium user) to work on this...
I just think it's not a good thing to have a 5 years old dependency in climetlab and that you should find a way to update it.

Until then, may be `branca==0.3.1` could only be an extra "interactive" dependency ?

**Comment by thebaptiste** [comment]
I saw you removed the exact dependency to `branca 0.31` in release 0.13.5.
Thanks, this issue can be closed.
